version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "properties-demo-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1uop7t5i7ns39"
s3_prefix = "properties-demo-api"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

